# Generated by Django 4.2.1 on 2023-06-27 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('None', 'None'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Other Comments', 'Other Comments'), ('Traning/documents request', 'Traning/documents Request'), ('Feature request', 'Feature Request'), ('Bugs/Errors', 'Bugs/Errors')], max_length=40),
        ),
    ]
