# Generated by Django 4.2.1 on 2023-06-27 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_comment_commenter_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('None', 'None')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Feature request', 'Feature Request'), ('Other Comments', 'Other Comments'), ('Bugs/Errors', 'Bugs/Errors'), ('Traning/documents request', 'Traning/documents Request')], max_length=40),
        ),
    ]
