# Generated by Django 4.2.2 on 2023-06-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_comment_commenter_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('None', 'None'), ('High', 'High')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Bugs/Errors', 'Bugs/Errors'), ('Other Comments', 'Other Comments'), ('Traning/documents request', 'Traning/documents Request'), ('Feature request', 'Feature Request')], max_length=40),
        ),
    ]
