# Generated by Django 4.2.2 on 2023-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_priority_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Bugs/Errors', 'Bugs/Errors'), ('Feature request', 'Feature Request'), ('Other Comments', 'Other Comments'), ('Traning/documents request', 'Traning/documents Request')], max_length=40),
        ),
    ]
