# Generated by Django 4.2.3 on 2023-07-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_attachments_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Attachments',
            new_name='attachments',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('None', 'None'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Other Comments', 'Other Comments'), ('Bugs/Errors', 'Bugs/Errors'), ('Traning/documents request', 'Traning/documents Request'), ('Feature request', 'Feature Request')], max_length=40),
        ),
    ]
