# Generated by Django 4.2.3 on 2023-07-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_priority_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Medium', 'Medium'), ('None', 'None'), ('High', 'High'), ('Low', 'Low')], max_length=40),
        ),
    ]
