# Generated by Django 4.2.3 on 2023-07-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Medium', 'Medium'), ('High', 'High'), ('None', 'None'), ('Low', 'Low')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Feature request', 'Feature Request'), ('Bugs/Errors', 'Bugs/Errors'), ('Traning/documents request', 'Traning/documents Request'), ('Other Comments', 'Other Comments')], max_length=40),
        ),
    ]
