# Generated by Django 4.2.1 on 2023-06-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created',
            new_name='created_at',
        ),
    ]
