# Generated by Django 4.2.1 on 2023-06-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Project Manager', 'Project Manager'), ('Submitter', 'Submitter'), ('Admin', 'Admin')], default='Developer', max_length=40, null=True),
        ),
    ]
